name: Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Patch theme
        run: |
          (cd themes/hugo-theme-cleanwhite; git pull)
          cat patch/footer.html themes/hugo-theme-cleanwhite/layouts/partials/footer.html > footer.html
          mv footer.html themes/hugo-theme-cleanwhite/layouts/partials
          sed -i  's/CATALOG/SECTIONS/' themes/hugo-theme-cleanwhite/layouts/_default/single.html
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install nb2hugo
        run:
          python -m pip install nb2hugo
        shell: bash

      - name: Convert notebooks
        run: |
          for i in notebooks/*.ipynb;do;nb2hugo "$i" --site-dir . --section post;done
        shell: bash

      - name: Build
        run: hugo --minify --baseURL=http://www.grahamwheeler.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


